### PR TITLE
Anne Ananwune Article

### PR DESCRIPTION
**Pull request by Matthabbey**

### CODE REVIEW

**Comment by Matthabbey** [comment]
@kaf-lamed-beyt 
Good morning. 
Please, how many commits am I supposed to push to a branch before it can be approved?
Thanks for your quick response.

**Comment by kaf-lamed-beyt** [comment]
There's no fixed amount of commits you can add to a pull request 😉 

So long as your changes fixes or does what is expected of it — in this case, adding an article, which you have done excellently well.

But, there's a conflict of interests with the package managers that we're using. Your changes extended yarn, but this project uses npm. 

If I go ahead and merge it like so, we'll be having two package management systems — yarn and npm — in one codebase, which isn't too good, and can lead to the project becoming bloated.

So what I need you to do, this time around is 👇🏽

- delete the `node_modules` folder
- delete `yarn.lock` file
- delete the `.vercel` folder too.
- run the command `npm install`. If this works correctly, you should be seeing a `package.lock.json` file and a new `node_modules` folder in your project directory.
- when you've tested your changes and you're still noticing that the `.vercel` file is in the codebase. You can stop git from tracking it, by adding it inside `.gitignore`

**Comment by Matthabbey** [comment]
Okay.
I read from the ReadMe file that yarn is supposed to be used, and that was exactly what I followed. I would immediately effect the change and send another PR. I trust there wouldn't be another complication this time. Though this is my first time and it is really getting more interesting. 
I am open to more open source contribution or if you have any side gigs or opportunity to extend, i would gladly jump on it. Thanks.

**Comment by kaf-lamed-beyt** [comment]
Oops! sorry about the misinformation. That was the default installation guide that came with `create-next-app` I'll make the change, and push it so that people are not misdirected again.

And I'm glad you're enjoying the overall process. Here's [another project](https://github.com/kaf-lamed-beyt/ng-tech-events) that I think might be interesting to contribute to.

Lest I forget, could you star this repo for me, when you're done with the changes? It sorta encourages me to do more 😌

**Pull request closed without merging**
